"""Pipeline orchestrator — the glue that ties every module together.

Run order, matching ``docs/techbrief.md``:

  1. Load source project_settings + model_settings from the uploaded 3mf
  2. Load the U1 reference profile
  3. Identity swap (printer_* keys, build volume, nozzle list, …)
  4. G-code swap
  5. Key filter (drop Bambu-only keys)
  6. Value clamp (speed / accel ceilings from the reference)
  7. Rules engine
  8. Advanced user overrides (from the UI, applied last so they win)
  9. Normalise filament_* arrays to 4 slots (U1 has 4 toolheads)
 10. Filament slot remap on model_settings.config
 11. Key-filter model_settings.config (no-op in v1 — we don't drop XML attrs)
 12. Strip Metadata/plate_*.gcode / plate_*.json slice caches
 13. Rezip as ``{original}-U1.3mf`` alongside a DiffReport JSON

The pipeline is pure over file contents — it reads a source path, reads a
reference path, and writes to an output path. Temp-dir handling + HTTP
concerns live in ``main.py``.
"""
from __future__ import annotations

import json
import logging
import re
import time
import zipfile
from dataclasses import dataclass
from pathlib import Path
from typing import Any
from xml.etree import ElementTree as ET

log = logging.getLogger("u13mf.converter")

from diff_reporter import DiffBuilder
from gcode_swapper import GCODE_KEYS, swap_gcode
from key_filter import clamp_numeric_ceilings, filter_to_schema
from metadata_helpers import (
    minimal_model_settings,
    minimal_slice_info,
    rewrite_custom_gcode_per_layer,
    rewrite_slice_info,
    translate_prusa_mmu_paint,
)
from models import ConversionSettings, DiffReport, RuleDefinition, SlotRemapEvent
from profile_loader import read_project_settings, read_source_settings
from rules_engine import FilamentContext, apply_rules
from swap_pauses import insert_swap_pauses

# Keys that must come from the U1 reference profile — strictly hardware identity.
# Everything else preserves source intent.
IDENTITY_COPY_KEYS: tuple[str, ...] = (
    "printer_settings_id",
    "printer_model",
    "printer_variant",
    "printable_area",
    "printable_height",
    "nozzle_diameter",
    "nozzle_type",
    "nozzle_volume",
    "compatible_printers",
    "compatible_printers_condition",
    "bed_exclude_area",
    # Orca protocol version — prevents "generated by a different application" warning.
    "version",
)

# Bambu uses "0" as an auto-sentinel for these filament-role slot keys; U1 Orca
# requires an explicit 1-based slot number.  Only the sentinel is replaced —
# any intentional non-zero assignment from the source is preserved.
_FILAMENT_SLOT_SENTINEL_KEYS: frozenset[str] = frozenset({
    "wall_filament",
    "sparse_infill_filament",
    "solid_infill_filament",
    "support_filament",
    "support_interface_filament",
    "wipe_tower_filament",
})

# Bambu uses -1 as an "inherit / auto" sentinel for these keys; Orca requires
# an explicit value.  When the source contains -1 we substitute the reference
# profile's value so Orca gets something valid.
_NEGATIVE_SENTINEL_KEYS: frozenset[str] = frozenset({
    "raft_first_layer_expansion",
    "tree_support_wall_count",
    "prime_tower_lift_height",
})

# Direct value remaps for Bambu enum strings that Orca does not recognise.
_VALUE_REMAP: dict[str, dict[str, str]] = {
    "ensure_vertical_shell_thickness": {"disabled": "none", "enabled": "ensure_all", "partial": "ensure_all"},
    "support_style": {"tree_organic": "default"},
}

# Snapmaker U1 has 4 physical toolheads.
_U1_TOOLHEADS_DEFAULT = 4

PROJECT_SETTINGS = "Metadata/project_settings.config"
MODEL_SETTINGS = "Metadata/model_settings.config"
SLICE_INFO = "Metadata/slice_info.config"
CUSTOM_GCODE_XML = "Metadata/custom_gcode_per_layer.xml"
MODEL_3D = "3D/3dmodel.model"

# Build items spanning more than this in X or Y are a multi-plate layout —
# skip the bed-origin shift for those files.  400mm rather than 300mm so
# that large H2D single-plate models (up to 350mm bed) are still shifted;
# genuine 2-plate layouts span ~700mm+ between plate centroids.
_MULTIPLATE_SPAN_MM = 400.0

# Clearance added beyond the U1 bed origin to avoid Orca's boundary warning.
_BED_MARGIN_MM = 3.0


def is_painted_model(archive_names: list[str], filament_count: int) -> bool:
    """True when the file likely uses painted geometry rather than per-layer colour G-code."""
    return CUSTOM_GCODE_XML not in archive_names and filament_count > 1

# Patterns for slice-cache artifacts we strip to force re-slice in Orca.
_SLICE_ARTIFACT_PATTERNS = (
    re.compile(r"^Metadata/plate_\d+\.gcode(\.md5)?$"),
    re.compile(r"^Metadata/plate_\d+\.json$"),
    re.compile(r"^Metadata/_rels/"),  # rels files reference gcode — dangling after strip
    # EXPERIMENTAL (commit 5b26e05+1): Orca per-preset embeds — strip to prevent
    # Bambu-tuned values overriding the merged U1 project_settings.config.
    # Roll back with: git checkout 5b26e05 -- backend/converter.py
    re.compile(r"^Metadata/process_settings_\d+\.config$"),
    re.compile(r"^Metadata/filament_settings_\d+\.config$"),
)

# Bambu-only metadata files that have no equivalent in Snapmaker Orca and
# would confuse it or bloat the output unnecessarily.
_BAMBU_ONLY_FILES: frozenset[str] = frozenset(
    {
        "Metadata/filament_sequence.json",
        "Metadata/cut_information.xml",
        "Metadata/auxiliary.xml",
    }
)

# Slicer-native metadata files that must not appear in Orca-format output.
_PRUSA_ONLY_FILES: frozenset[str] = frozenset(
    {
        "Metadata/Slic3r_PE.config",
        "Metadata/Slic3r_PE_model.config",
        "Metadata/Prusa_Slicer_wipe_tower_information.xml",
    }
)


# ---------------------------------------------------------------------------


@dataclass
class ConversionResult:
    output_path: Path
    diff: DiffReport


def convert(
    *,
    source_path: Path,
    reference_path: Path,
    output_path: Path,
    settings: ConversionSettings,
    rules: list[RuleDefinition],
    preserve_bambu_metadata: bool = False,
) -> ConversionResult:
    """Run the full pipeline. Returns the output path + DiffReport.

    ``preserve_bambu_metadata`` — when True, Bambu-specific metadata files
    (filament_sequence.json, cut_information.xml, auxiliary.xml) are kept in
    the output and model_settings.config is not rewritten.  Use this for
    Bambu-to-Bambu cross-printer conversion where those files remain valid.
    """
    t0 = time.monotonic()
    src_size = source_path.stat().st_size
    log.info(
        "START  %s  (%.1f KB)  profile=%s  rules=%s  clamp=%s  painting=%s",
        source_path.name,
        src_size / 1024,
        reference_path.stem,
        settings.apply_rules,
        settings.clamp_speeds,
        settings.preserve_color_painting,
    )

    source_cfg, _ = read_source_settings(source_path)
    reference_cfg = read_project_settings(reference_path)

    with zipfile.ZipFile(source_path) as _znames:
        _src_names = _znames.namelist()
    _is_painted = is_painted_model(_src_names, len(source_cfg.get("filament_settings_id") or []))

    src_printer = source_cfg.get("printer_model", "?")
    src_lh = source_cfg.get("layer_height", "?")
    src_filaments = source_cfg.get("filament_settings_id") or []
    log.info(
        "SOURCE printer=%s  layer_height=%s  filaments=%s",
        src_printer,
        src_lh,
        src_filaments,
    )

    diff = DiffBuilder(
        source_filename=source_path.name,
        output_filename=output_path.name,
        reference_profile=reference_path.stem,
    )

    # 3. identity swap
    merged = _apply_identity_swap(source_cfg, reference_cfg, diff)
    # Append suffix so Orca cannot exact-match a U1 library profile and load
    # its defaults over the embedded source settings.
    if merged.get("print_settings_id"):
        merged["print_settings_id"] = merged["print_settings_id"] + " (converted)"
    id_swaps = len(diff.build().identity_swaps)
    log.info("STAGE  identity-swap: %d keys updated", id_swaps)

    # 4. g-code swap
    merged, gcode_events = swap_gcode(merged, reference_cfg)
    diff.extend_gcode_swaps(gcode_events)
    log.info("STAGE  gcode-swap: %d blocks replaced", len(gcode_events))

    # 5. key filter against reference schema
    schema_keys = set(reference_cfg.keys())
    # custom_gcode_per_layer: per-layer colour-swap/pause markers absent from reference but needed by Orca.
    # internal_bridge_support_thickness: present in fdm_process_common at default (0.8) so not written
    # to reference .3mf exports, but is a valid Orca print-intent key that should flow from source.
    merged, dropped = filter_to_schema(
        merged,
        schema_keys,
        keep_keys=["custom_gcode_per_layer", "internal_bridge_support_thickness"],
    )
    diff.extend_keys_dropped(dropped)
    log.info("STAGE  key-filter: %d keys dropped", len(dropped))

    # Re-overlay reference defaults for any key absent from source.
    for k, v in reference_cfg.items():
        merged.setdefault(k, v)

    # Snapmaker Orca has a bug with rib prime towers; force rectangle (normal)
    # tower mode in U1 output regardless of source.  Bambu uses different keys
    # (prime_tower_fillet_wall / prime_tower_rib_wall) that are stripped by the
    # key filter, so without this the output inherits whatever the reference has.
    if not preserve_bambu_metadata:
        merged["wipe_tower_wall_type"] = "rectangle"

    # For Bambu-to-Bambu: overwrite print_compatible_printers from the reference
    # so Bambu Studio recognises the target printer instead of showing the source
    # printer's compatible list (e.g. X1C/P1S list on an H2S file).
    if preserve_bambu_metadata and "print_compatible_printers" in reference_cfg:
        merged["print_compatible_printers"] = reference_cfg["print_compatible_printers"]

    # Clear inherits_group — it names library profiles (print + per-filament)
    # that Orca will load and apply on top of embedded settings, overriding
    # source values like initial_layer_print_height and filament_settings_id.
    if "inherits_group" in merged:
        n = len(merged["inherits_group"]) if isinstance(merged["inherits_group"], list) else 0
        merged["inherits_group"] = [""] * n

    # 5b. collapse per-extruder lists → scalars where reference uses a scalar.
    # Bambu stores many settings as [val_ext1, val_ext2, ...]; U1 Orca expects
    # a single value.  Take the first element so source intent is preserved;
    # the clamp step that follows will cap it to U1 limits.
    merged = _collapse_extruder_lists(merged, reference_cfg)
    log.info("STAGE  collapse-lists: done")

    # 5c. Filament-role slot sentinels: Bambu uses "0" (auto); U1 needs explicit "1".
    n_slot = 0
    for key in _FILAMENT_SLOT_SENTINEL_KEYS:
        if merged.get(key) in ("0", 0):
            merged[key] = "1"
            n_slot += 1

    # 5d-pre. Zero line-width sentinels: Bambu uses 0 to mean "derive from nozzle
    # diameter." When the source nozzle differs from the U1's (e.g. 0.2mm → 0.4mm)
    # these zeros produce 0-width paths in Orca, breaking both printing and
    # paint-driven filament changes. Replace with reference value.
    n_lw = 0
    for key, val in list(merged.items()):
        if not (key == "line_width" or key.endswith("_line_width")):
            continue
        if key == "brim_width":
            continue  # 0 = no brim, intentional
        try:
            if float(str(val)) == 0.0 and key in reference_cfg:
                ref_val = reference_cfg[key]
                if float(str(ref_val)) > 0:
                    merged[key] = ref_val
                    n_lw += 1
        except (TypeError, ValueError):
            pass
    if n_lw:
        log.info("STAGE  sentinels: lw_zero=%d", n_lw)

    # 5d. Negative sentinels: Bambu uses -1 (inherit); substitute reference value.
    n_neg = 0
    for key in _NEGATIVE_SENTINEL_KEYS:
        try:
            if float(str(merged.get(key))) == -1.0 and key in reference_cfg:
                merged[key] = reference_cfg[key]
                n_neg += 1
        except (TypeError, ValueError):
            pass

    # 5e. Enum remaps: Bambu enum strings Orca doesn't recognise.
    n_enum = 0
    for key, mapping in _VALUE_REMAP.items():
        val = merged.get(key)
        if isinstance(val, str) and val in mapping:
            merged[key] = mapping[val]
            n_enum += 1

    if n_slot or n_neg or n_enum:
        log.info("STAGE  sentinels: slot=%d neg=%d enum=%d lw=%d", n_slot, n_neg, n_enum, n_lw)

    # 6. clamp speed / accel ceilings
    if settings.clamp_speeds:
        merged, clamp_events = clamp_numeric_ceilings(merged, reference_cfg)
        diff.extend_values_clamped(clamp_events)
        log.info("STAGE  clamp: %d values clamped", len(clamp_events))
    else:
        log.info("STAGE  clamp: skipped")

    # 6b. disable prime tower when variable layer height is present.
    # Two separate VLH mechanisms both conflict with the prime tower:
    #   layer_config_ranges.xml  — per-layer settings ranges (colour/speed changes)
    #   layer_heights_profile.txt — per-object adaptive height data
    _HAS_LAYER_RANGES = "Metadata/layer_config_ranges.xml"
    _HAS_VLH_PROFILE = "Metadata/layer_heights_profile.txt"
    _has_vlh = _HAS_LAYER_RANGES in _src_names or _HAS_VLH_PROFILE in _src_names
    log.info("STAGE  vlh: %s", _has_vlh)
    if merged.get("enable_prime_tower") in ("1", 1) and _has_vlh:
        merged["enable_prime_tower"] = "0"
        log.info("STAGE  prime-tower: disabled — VLH present (layer_config_ranges or layer_heights_profile)")

    # 6c. organic supports + per-object VLH → Orca cannot slice; fall back to normal(auto)
    # layer_heights_profile.txt carries per-object adaptive height data; tree supports
    # are incompatible with it in Orca.
    _support_type = merged.get("support_type", "")
    if "tree" in str(_support_type) and _HAS_VLH_PROFILE in _src_names:
        merged["support_type"] = "normal(auto)"
        log.info("STAGE  supports: tree→normal(auto) — layer_heights_profile.txt present (VLH conflict)")

    # 7. rules engine
    if settings.apply_rules and rules:
        ctx = FilamentContext.from_settings(source_cfg)
        merged, rule_events = apply_rules(merged, rules, ctx)
        diff.extend_rules_matched(rule_events)
        for ev in rule_events:
            log.info(
                "RULE   %r (priority %d) matched — %d overrides applied",
                ev.rule_name,
                ev.priority,
                len(ev.overrides_applied),
            )
        if not rule_events:
            log.info("STAGE  rules: no rules matched")
    else:
        log.info("STAGE  rules: skipped (apply_rules=%s, n_rules=%d)",
                 settings.apply_rules, len(rules))

    # 8. advanced per-key overrides
    for k, v in settings.advanced_overrides.items():
        merged[k] = v
        diff.record_advanced_override(k, v)
    if settings.advanced_overrides:
        log.info("STAGE  advanced-overrides: %d keys", len(settings.advanced_overrides))

    # 9. filament array normalisation — preserve source slot count exactly.
    # For Bambu-to-Bambu the source count is authoritative (AMS handles any
    # number of slots).  For U1: if the user supplied an explicit slot_map
    # they are committing to a 4-toolhead output; otherwise pass all source
    # slots through so painted models keep every colour for Orca to handle.
    n_src = len(source_cfg.get("filament_settings_id") or [])
    n_ref = len(reference_cfg.get("filament_settings_id") or []) or _U1_TOOLHEADS_DEFAULT
    if preserve_bambu_metadata and n_src > 0:
        n_target = n_src
    elif settings.slot_map:
        n_target = _U1_TOOLHEADS_DEFAULT
    elif _is_painted:
        # No slot_map: skip was chosen — preserve all source colours so Orca
        # can handle slot assignment at re-slice time.
        n_target = n_src
    else:
        _is_non_orca = "printer_model" not in source_cfg
        if n_src > 0:
            # Non-Orca sources (PrusaSlicer, Cura) carry their own filament
            # arrays — pass them all through; don't cap at the reference slot
            # count which is tuned for Bambu prints.
            n_target = n_src if _is_non_orca else min(n_src, n_ref)
        elif "filament_settings_id" in source_cfg:
            # Orca/Bambu source with an explicit empty filament list.
            n_target = n_ref
        else:
            # Non-Orca source with no filament info at all — default to 1 slot.
            n_target = 1
    remap = _normalise_filament_arrays(
        merged, source_cfg, diff, slot_map=settings.slot_map or {}, n_target=n_target
    )
    # Clip or pad per-slot hardware arrays not handled by _normalise_filament_arrays.
    for _hw_key in ("nozzle_diameter", "nozzle_type", "nozzle_volume"):
        _hw_val = merged.get(_hw_key)
        if isinstance(_hw_val, list) and _hw_val:
            if len(_hw_val) > n_target:
                merged[_hw_key] = _hw_val[:n_target]
            elif len(_hw_val) < n_target:
                merged[_hw_key] = _hw_val + [_hw_val[-1]] * (n_target - len(_hw_val))
    log.info("STAGE  filament-normalise: remap=%s", remap)

    # 9b. For Bambu-to-Bambu: remap each source filament slot to the closest
    # target-printer-certified profile from the reference, matched by filament
    # type.  Source filament colours and embedded temps/speeds are preserved;
    # only the profile identity (settings_id, filament_ids, nozzle_map) changes
    # so Bambu Studio can validate the filament against the target nozzle.
    if preserve_bambu_metadata:
        _map_filaments_to_reference(merged, source_cfg, reference_cfg, n_target)
        log.info("STAGE  filament-profile-remap: done")

    # 9c. For Bambu-to-Bambu: rebuild strided filament arrays.
    # Some H2S-specific arrays (e.g. filament_extruder_variant) have 2 entries
    # per slot — one for Standard extruder, one for High Flow.  The source
    # (P1S/X1C) has no such key, so the reference value lands via setdefault.
    # _normalise_filament_arrays then truncates it to n_target entries instead
    # of stride * n_target, breaking HF availability in Bambu Studio.
    # Fix: detect stride from reference slot count and rebuild those arrays.
    if preserve_bambu_metadata:
        n_ref_slots = len(reference_cfg.get("filament_settings_id") or [])
        if n_ref_slots > 0:
            for _key, _ref_val in reference_cfg.items():
                if not _key.startswith("filament_") or not isinstance(_ref_val, list):
                    continue
                if source_cfg.get(_key):  # source had this; normalization was correct
                    continue
                if len(_ref_val) % n_ref_slots != 0:
                    continue
                _stride = len(_ref_val) // n_ref_slots
                if _stride <= 1:
                    continue
                if _key == "filament_self_index":
                    # Self-index is the 1-based slot number for each variant
                    # entry, not a repeatable pattern — must be generated.
                    merged[_key] = [str(s + 1) for s in range(n_target) for _ in range(_stride)]
                else:
                    _slot_pattern = _ref_val[:_stride]
                    merged[_key] = _slot_pattern * n_target
        log.info("STAGE  filament-stride-fix: done (n_ref_slots=%d)", n_ref_slots)

    # 10. optional swap-pause insertion for >4 colour prints
    custom_gcode_xml_override: str | None = None
    if settings.insert_swap_pauses:
        with zipfile.ZipFile(source_path) as _zcheck:
            if CUSTOM_GCODE_XML in _zcheck.namelist():
                raw_xml = _zcheck.read(CUSTOM_GCODE_XML).decode("utf-8")
                colours = merged.get("filament_colour") or []
                pause_cmd = merged.get("machine_pause_gcode", "M600")
                modified_xml, swap_instrs = insert_swap_pauses(
                    raw_xml, remap, colours, pause_cmd
                )
                if swap_instrs:
                    # Swap insertion adds new type=1 pause markers but must not
                    # leave any existing Bambu type=1 commands untouched.
                    custom_gcode_xml_override = rewrite_custom_gcode_per_layer(
                        modified_xml, pause_cmd
                    )
                    diff._report.swap_instructions = swap_instrs
                    log.info("STAGE  swap-pauses: %d pauses inserted", len(swap_instrs))
            else:
                # No per-layer G-code file — this is a painted model. Colour
                # changes are encoded in the model geometry and generated by the
                # slicer at re-slice time; pauses cannot be pre-inserted.
                diff._report.swap_pauses_skipped_painted = True
                log.info("STAGE  swap-pauses: skipped — no custom_gcode_per_layer.xml (painted model)")

    # 11–14. build output archive
    target_printer_model = reference_cfg.get("printer_model", "")
    _write_output_archive(
        source_path=source_path,
        reference_path=reference_path,
        output_path=output_path,
        new_project_settings=merged,
        remap=remap,
        diff=diff,
        settings=settings,
        custom_gcode_xml_override=custom_gcode_xml_override,
        preserve_bambu_metadata=preserve_bambu_metadata,
        target_printer_model=target_printer_model,
    )

    report = diff.build()
    out_size = output_path.stat().st_size
    elapsed = (time.monotonic() - t0) * 1000
    counts = report.counts()
    log.info(
        "DONE   %s  (%.1f KB)  elapsed=%.0f ms  "
        "identity=%d  gcode=%d  dropped=%d  clamped=%d  rules=%d  slots=%d",
        output_path.name,
        out_size / 1024,
        elapsed,
        counts.get("identity_swaps", 0),
        counts.get("gcode_swaps", 0),
        counts.get("keys_dropped", 0),
        counts.get("values_clamped", 0),
        counts.get("rules_matched", 0),
        counts.get("slot_remaps", 0),
    )

    return ConversionResult(output_path=output_path, diff=report)


# ---------------------------------------------------------------------------
# identity + filament helpers


def _apply_identity_swap(
    source_cfg: dict[str, Any],
    reference_cfg: dict[str, Any],
    diff: DiffBuilder,
) -> dict[str, Any]:
    merged = dict(source_cfg)
    for key in IDENTITY_COPY_KEYS:
        if key not in reference_cfg:
            continue
        old = merged.get(key)
        new = reference_cfg[key]
        if old != new:
            diff.record_identity_swap(key, old, new)
        merged[key] = new
    return merged


def _collapse_extruder_lists(
    settings: dict[str, Any],
    reference: dict[str, Any],
) -> dict[str, Any]:
    """Collapse per-extruder list values to scalars where reference expects a scalar.

    Bambu stores many print settings as [val_ext0, val_ext1, ...].  For keys
    where the U1 reference profile uses a single scalar, take the first element
    so downstream clamping operates on a comparable type.  filament_* arrays are
    intentionally excluded — they are handled by ``_normalise_filament_arrays``.
    """
    out = dict(settings)
    for key, ref_val in reference.items():
        if key.startswith("filament_") or key not in out:
            continue
        cur_val = out[key]
        if isinstance(cur_val, list) and not isinstance(ref_val, list):
            out[key] = cur_val[0] if cur_val else ref_val
    return out


def _map_filaments_to_reference(
    merged: dict[str, Any],
    source_cfg: dict[str, Any],
    reference_cfg: dict[str, Any],
    n_target: int,
) -> None:
    """Replace source filament profiles with target-printer-certified equivalents.

    Source filament_type is matched against reference filament_type to find
    the closest certified profile (e.g. PLA → Bambu PLA Basic @BBL H2S).
    filament_settings_id, filament_ids, and filament_nozzle_map are updated;
    filament_colour and all embedded temp/speed settings are kept from source.
    """
    src_types = source_cfg.get("filament_type") or []
    src_sids = source_cfg.get("filament_settings_id") or []
    ref_types = reference_cfg.get("filament_type") or []
    ref_sids = reference_cfg.get("filament_settings_id") or []
    ref_fids = reference_cfg.get("filament_ids") or []
    ref_nmap = reference_cfg.get("filament_nozzle_map") or []

    # Build type→ref map, preferring "Basic" profiles as the generic fallback
    # so that unknown/generic source filaments land on the most permissive
    # certified profile rather than the first alphabetical one.
    type_to_ref: dict[str, int] = {}
    for i, (t, sid) in enumerate(zip(ref_types, ref_sids)):
        if t not in type_to_ref or "basic" in sid.lower():
            type_to_ref[t] = i

    # Extract distinguishing keywords from each reference profile name so we
    # can match a source "Bambu PLA Matte" → Matte ref, "Silk" → Silk+ ref.
    _VARIANT_KEYWORDS = ["matte", "silk", "basic", "high flow", " hf"]
    keyword_to_ref: dict[str, int] = {}
    for i, sid in enumerate(ref_sids):
        sid_l = sid.lower()
        for kw in _VARIANT_KEYWORDS:
            if kw in sid_l and kw not in keyword_to_ref:
                keyword_to_ref[kw] = i

    new_sids, new_fids, new_nmap = [], [], []
    for i in range(n_target):
        src_type = src_types[i] if i < len(src_types) else "PLA"
        src_sid = (src_sids[i] if i < len(src_sids) else "").lower()

        # 1. keyword match — preserves Matte→Matte, Silk→Silk+, etc.
        ref_idx = next(
            (keyword_to_ref[kw] for kw in _VARIANT_KEYWORDS if kw in src_sid and kw in keyword_to_ref),
            None,
        )
        # 2. type match (Basic-preferred fallback)
        if ref_idx is None:
            ref_idx = type_to_ref.get(src_type)

        if ref_idx is not None:
            new_sids.append(ref_sids[ref_idx] if ref_idx < len(ref_sids) else f"Generic {src_type}")
            new_fids.append(ref_fids[ref_idx] if ref_idx < len(ref_fids) else "")
            new_nmap.append("1")
        else:
            # No type match — keep as Generic and use Standard nozzle.
            new_sids.append(f"Generic {src_type}" if src_type else "Generic PLA")
            cur_fids = merged.get("filament_ids") or []
            new_fids.append(cur_fids[i] if i < len(cur_fids) else "")
            new_nmap.append("0")

    merged["filament_settings_id"] = new_sids
    merged["filament_ids"] = new_fids
    merged["filament_nozzle_map"] = new_nmap


def _normalise_filament_arrays(
    merged: dict[str, Any],
    source_cfg: dict[str, Any],
    diff: DiffBuilder,
    slot_map: dict[int, int] | None = None,
    n_target: int = _U1_TOOLHEADS_DEFAULT,
) -> dict[int, int]:
    """Reorder, pad, and truncate every ``filament_*`` array to n_target slots.

    ``slot_map`` is 0-indexed source_slot → 0-indexed target_toolhead.
    If empty/None the identity map is used (slot N → toolhead N).
    Source slots that map beyond n_target are dropped; unpopulated target
    slots are filled by repeating the last mapped entry.
    """
    source_ids = source_cfg.get("filament_settings_id") or []
    n_src = len(source_ids)

    # Build the canonical remap: every source slot → target toolhead.
    remap: dict[int, int] = {}
    for i in range(n_src):
        if slot_map and i in slot_map:
            target = slot_map[i]
        else:
            target = i
        if target >= n_target:
            target = -1  # dropped
        remap[i] = target

    for i, target in remap.items():
        diff.extend_slot_remaps(
            [SlotRemapEvent(
                from_index=i,
                to_index=target,
                filament_id=source_ids[i] if i < len(source_ids) else None,
            )]
        )

    # Reorder every filament_* list according to the remap.
    for key, value in list(merged.items()):
        if not (key.startswith("filament_") and isinstance(value, list)):
            continue
        if not value:
            continue

        # Build a target-length list, placing source values at mapped positions.
        # First-write wins: primary slots (lower index) take precedence over
        # overflow colours merged into the same target.
        out: list[Any] = [None] * n_target
        fallback = value[-1] if value else None
        for src_i, tgt_i in remap.items():
            if tgt_i >= 0 and src_i < len(value) and out[tgt_i] is None:
                out[tgt_i] = value[src_i]

        # Fill any unpopulated target slots with the fallback (last source value).
        for j in range(n_target):
            if out[j] is None:
                out[j] = fallback

        merged[key] = out

    return remap


# ---------------------------------------------------------------------------
# archive writer


def _bed_shift(
    model_xml: str,
    src_printable_area: list[str],
    ref_printable_area: list[str],
) -> tuple[str, bool]:
    """Shift build item translations so objects clear the U1 bed origin.

    Bambu beds start at (0, 0); the U1 bed starts at (0.5, 1).  Models that
    fill the source bed to its front/left edge land 1mm off the U1 plate.

    For multi-plate files (build items spread > _MULTIPLATE_SPAN_MM), skip
    the shift — each plate has its own world-space offset and a uniform
    translation would misalign all but the first plate.

    Returns (possibly-modified xml, shifted: bool).
    """
    transforms = re.findall(r'transform="([^"]+)"', model_xml)
    if not transforms:
        return model_xml, False

    txs = []
    tys = []
    for t in transforms:
        vals = t.split()
        if len(vals) == 12:
            txs.append(float(vals[9]))
            tys.append(float(vals[10]))

    if not txs:
        return model_xml, False

    if (max(txs) - min(txs)) > _MULTIPLATE_SPAN_MM or (max(tys) - min(tys)) > _MULTIPLATE_SPAN_MM:
        return model_xml, False  # multi-plate — skip

    def _parse_min(area: list[str]) -> tuple[float, float]:
        xs, ys = [], []
        for pt in area:
            x, y = pt.split("x")
            xs.append(float(x)); ys.append(float(y))
        return min(xs), min(ys)

    src_ox, src_oy = _parse_min(src_printable_area)
    ref_ox, ref_oy = _parse_min(ref_printable_area)
    dx = (ref_ox - src_ox) + _BED_MARGIN_MM
    dy = (ref_oy - src_oy) + _BED_MARGIN_MM

    if abs(dx) < 1e-6 and abs(dy) < 1e-6:
        return model_xml, False

    def _replace(m: re.Match) -> str:
        vals = m.group(1).split()
        if len(vals) != 12:
            return m.group(0)
        vals[9] = f"{float(vals[9]) + dx:.6g}"
        vals[10] = f"{float(vals[10]) + dy:.6g}"
        return f'transform="{" ".join(vals)}"'

    return re.sub(r'transform="([^"]+)"', _replace, model_xml), True


def _write_output_archive(
    *,
    source_path: Path,
    reference_path: Path,
    output_path: Path,
    new_project_settings: dict[str, Any],
    remap: dict[int, int],
    diff: DiffBuilder,
    settings: ConversionSettings,
    custom_gcode_xml_override: str | None = None,
    preserve_bambu_metadata: bool = False,
    target_printer_model: str = "Snapmaker U1",
) -> None:
    new_proj_bytes = json.dumps(
        new_project_settings, indent=4, ensure_ascii=False
    ).encode("utf-8")

    # Read source bed extents for the build-item shift calculation.
    with zipfile.ZipFile(source_path, "r") as _zpa:
        _src_area = (
            json.loads(_zpa.read(PROJECT_SETTINGS).decode("utf-8")).get("printable_area")
            if PROJECT_SETTINGS in _zpa.namelist() else None
        ) or ["0x0"]
    _ref_area = new_project_settings.get("printable_area") or ["0x0"]

    with zipfile.ZipFile(source_path, "r") as zin, zipfile.ZipFile(
        output_path, "w", compression=zipfile.ZIP_DEFLATED
    ) as zout:

        # Collect the reference's model_settings once, in case we need to
        # fall back to it (e.g. if source has none).
        with zipfile.ZipFile(reference_path, "r") as zref:
            ref_model_settings = (
                zref.read(MODEL_SETTINGS).decode("utf-8")
                if MODEL_SETTINGS in zref.namelist()
                else None
            )

        for item in zin.infolist():
            name = item.filename

            # Zip-slip defence — skip anything with traversal components.
            if name.startswith("/") or ".." in name.split("/"):
                continue

            # Slice-cache artifacts always stripped; Bambu-only metadata
            # stripped only for U1 output (irrelevant to Snapmaker Orca).
            strip_bambu = not preserve_bambu_metadata and name in _BAMBU_ONLY_FILES
            strip_foreign = name in _PRUSA_ONLY_FILES or name.startswith("Cura/")
            if _is_slice_artifact(name) or strip_bambu or strip_foreign:
                diff.record_slice_artifact_stripped(name)
                continue

            if name == PROJECT_SETTINGS:
                zout.writestr(name, new_proj_bytes)
                continue

            if name == MODEL_3D and not preserve_bambu_metadata:
                model_xml = zin.read(MODEL_3D).decode("utf-8")
                # For non-Orca sources: replace PrusaSlicer namespace with BambuStudio
                # namespace so Orca accepts the file as a valid project rather than
                # falling back to geometry-only mode.
                if 'xmlns:slic3rpe=' in model_xml:
                    model_xml, paint_attrs = translate_prusa_mmu_paint(model_xml)
                    model_xml = re.sub(r'\s+xmlns:slic3rpe="[^"]*"', "", model_xml)
                    model_xml = re.sub(r'\s+slic3rpe:\w+="[^"]*"', "", model_xml)
                    model_xml = re.sub(r'\s*<metadata\s+name="slic3rpe:[^"]*">[^<]*</metadata>', "", model_xml)
                    model_xml = re.sub(
                        r'<metadata name="Application">[^<]*</metadata>',
                        '<metadata name="Application">BambuStudio-2.3.1</metadata>',
                        model_xml,
                        count=1,
                    )
                    model_xml = re.sub(
                        r'(<model\b[^>]*)(>)',
                        r'\1 xmlns:BambuStudio="http://schemas.bambulab.com/package/2021"\2',
                        model_xml, count=1,
                    )
                    if 'BambuStudio:3mfVersion' not in model_xml:
                        model_xml = model_xml.replace(
                            '<resources>',
                            '<metadata name="BambuStudio:3mfVersion">1</metadata>\n <resources>',
                            1,
                        )
                    if paint_attrs:
                        log.info("STAGE  prusa-paint: %d mmu_segmentation attrs → paint_color", paint_attrs)
                shifted_xml, was_shifted = _bed_shift(model_xml, _src_area, _ref_area)
                zout.writestr(item, shifted_xml.encode("utf-8"))
                if was_shifted:
                    log.info("STAGE  bed-shift: build items shifted to U1 bed origin")
                else:
                    log.info("STAGE  bed-shift: skipped (multi-plate or no shift needed)")
                continue

            if name == MODEL_SETTINGS and not preserve_bambu_metadata:
                modified = _rewrite_model_settings(
                    zin.read(MODEL_SETTINGS).decode("utf-8"), remap
                )
                zout.writestr(name, modified)
                continue

            if name == SLICE_INFO:
                modified = rewrite_slice_info(
                    zin.read(SLICE_INFO).decode("utf-8"),
                    target_printer_model,
                )
                zout.writestr(name, modified)
                continue

            if name == CUSTOM_GCODE_XML:
                # Use pre-processed XML (with swap pauses) if available.
                if custom_gcode_xml_override is not None:
                    zout.writestr(name, custom_gcode_xml_override)
                else:
                    pause_cmd = new_project_settings.get("machine_pause_gcode", "M600")
                    modified = rewrite_custom_gcode_per_layer(
                        zin.read(CUSTOM_GCODE_XML).decode("utf-8"), pause_cmd
                    )
                    zout.writestr(name, modified)
                continue

            # Everything else copies through verbatim.
            zout.writestr(item, zin.read(name))

        # If source had no project_settings (non-Orca format), write the merged one now.
        with zipfile.ZipFile(source_path, "r") as zin_check:
            src_names = zin_check.namelist()
        if PROJECT_SETTINGS not in src_names:
            zout.writestr(PROJECT_SETTINGS, new_proj_bytes)
            # Generate a minimal model_settings.config from actual object IDs in the
            # source model so Orca can load the scene without reference object confusion.
            if MODEL_SETTINGS not in src_names:
                zout.writestr(MODEL_SETTINGS, minimal_model_settings(src_names, source_path))
            # Orca requires slice_info.config to recognise the file as a project.
            if SLICE_INFO not in src_names:
                zout.writestr(SLICE_INFO, minimal_slice_info(target_printer_model))
            # Orca's web layer expects plate_1.json; missing file causes JSON parse error.
            if "Metadata/plate_1.json" not in src_names:
                zout.writestr("Metadata/plate_1.json", json.dumps({
                    "filament_colors": new_project_settings.get("filament_colour") or [],
                    "filament_ids": new_project_settings.get("filament_settings_id") or [],
                    "first_extruder": 0,
                    "is_seq_print": False,
                    "version": 2,
                }))
        elif MODEL_SETTINGS not in src_names and ref_model_settings:
            # Orca source had no model_settings — seed from reference as before.
            zout.writestr(MODEL_SETTINGS, ref_model_settings)


def _is_slice_artifact(name: str) -> bool:
    return any(p.match(name) for p in _SLICE_ARTIFACT_PATTERNS)


def _rewrite_model_settings(xml_text: str, remap: dict[int, int]) -> str:
    """Rewrite per-object ``extruder`` metadata and plate ``filament_maps``.

    The remap here is 0-indexed (source_slot -> target_slot). XML stores
    extruder values as 1-indexed strings, so we translate.
    """
    try:
        root = ET.fromstring(xml_text)
    except ET.ParseError:
        # Pass malformed XML through unchanged rather than failing the
        # whole conversion — the user can still open the file and diagnose.
        return xml_text

    # Orca errors if objects have different raft layer counts when prime tower
    # is enabled.  Collect all explicit raft_layers values; treat absent as
    # "0".  If the effective set has >1 distinct value, normalise all to "0".
    raft_metas = [m for m in root.iter("metadata") if m.get("key") == "raft_layers"]
    effective_raft = {m.get("value", "0") for m in raft_metas}
    if len(raft_metas) < sum(1 for _ in root.iter("object")):
        effective_raft.add("0")  # some objects have no raft_layers → implicit 0
    if len(effective_raft) > 1:
        for m in raft_metas:
            m.set("value", "0")

    for meta in root.iter("metadata"):
        key = meta.get("key")
        if key in _VALUE_REMAP:
            val = meta.get("value")
            if val in _VALUE_REMAP[key]:
                meta.set("value", _VALUE_REMAP[key][val])
        if meta.get("key") == "extruder":
            raw = meta.get("value")
            if raw is None:
                continue
            try:
                old_1based = int(raw)
            except ValueError:
                continue
            old_0based = old_1based - 1
            if old_0based in remap:
                new_0based = remap[old_0based]
                if new_0based < 0:
                    # Filament was dropped — clamp to toolhead 1.
                    new_1based = 1
                else:
                    new_1based = new_0based + 1
                meta.set("value", str(new_1based))
        elif meta.get("key") == "filament_maps":
            # Set every slot to its own toolhead index (1-indexed), clipped
            # to the U1 toolhead count. This matches the identity remap and
            # distributes Bambu's all-on-extruder-1 default across U1's
            # four heads.
            raw = meta.get("value", "")
            slots = raw.split()
            new_slots: list[str] = []
            for i in range(len(slots)):
                # filament_maps is per-object toolhead routing for non-painted
                # models. For painted models the paint_color mesh attributes
                # drive colour output at re-slice time, making these values
                # largely irrelevant — Orca re-derives them on re-slice.
                # The remap dict is intentionally NOT applied here: for
                # non-painted identity remaps this formula is correct for
                # slots 0-3, and for painted models it doesn't matter.
                toolhead = (i % _U1_TOOLHEADS_DEFAULT) + 1
                new_slots.append(str(toolhead))
            meta.set("value", " ".join(new_slots) if new_slots else raw)

    return ET.tostring(root, encoding="unicode", xml_declaration=False)
