<script lang="ts">
  import type { DiffPayload } from './api';
  import { downloadUrl } from './api';

  interface Props {
    diff: DiffPayload;
    jobId: string;
    downloadName: string;
    onreset: () => void;
  }

  let { diff, jobId, downloadName, onreset }: Props = $props();

  let expanded = $state<Set<number>>(new Set());

  function toggle(i: number) {
    const s = new Set(expanded);
    if (s.has(i)) s.delete(i); else s.add(i);
    expanded = s;
  }

  // Auto-expand swap instructions section if present.
  $effect(() => {
    const idx = diff.sections.findIndex(s => s.title === 'Filament swap pauses');
    if (idx >= 0) expanded = new Set([idx]);
  });

  function formatValue(v: unknown): string {
    if (v === null || v === undefined) return '—';
    if (Array.isArray(v)) return v.join(', ');
    return String(v);
  }

  let counts = $derived(diff.counts);
</script>

<div class="diff-view">
  <div class="header">
    <div class="header-left">
      <h2>Conversion complete</h2>
      <div class="meta muted">
        {diff.report.source_filename} →
        <strong class="accent">{diff.report.output_filename}</strong>
      </div>
    </div>
    <div class="header-actions">
      <button class="ghost" onclick={onreset}>Convert another</button>
      <a
        href={downloadUrl(jobId)}
        download={downloadName}
        class="download-btn"
      >
        Download .3mf
      </a>
    </div>
  </div>

  {#if diff.report.swap_pauses_skipped_painted}
    <div class="painted-warning" role="alert">
      <strong>Swap pauses not inserted:</strong> this is a painted model — colour
      changes are generated by the slicer at re-slice time. Configure filament swap
      pauses in Snapmaker Orca after re-slicing.
    </div>
  {/if}

  <div class="pills">
    {#if counts.identity_swaps}
      <span class="pill success">✓ {counts.identity_swaps} identity keys</span>
    {/if}
    {#if counts.gcode_swaps}
      <span class="pill success">✓ {counts.gcode_swaps} G-code blocks</span>
    {/if}
    {#if counts.keys_dropped}
      <span class="pill">✕ {counts.keys_dropped} keys dropped</span>
    {/if}
    {#if counts.values_clamped}
      <span class="pill warn">⇩ {counts.values_clamped} values clamped</span>
    {/if}
    {#if counts.rules_matched}
      <span class="pill accent">⚙ {counts.rules_matched} rules matched</span>
    {/if}
    {#if counts.slot_remaps}
      <span class="pill">⇆ {counts.slot_remaps} filament slots</span>
    {/if}
    {#if counts.slice_artifacts_stripped}
      <span class="pill">✕ {counts.slice_artifacts_stripped} caches stripped</span>
    {/if}
    {#if counts.advanced_overrides_applied}
      <span class="pill accent">+ {counts.advanced_overrides_applied} overrides</span>
    {/if}
    {#if counts.swap_instructions}
      <span class="pill warn">⏸ {counts.swap_instructions} filament swap{counts.swap_instructions > 1 ? 's' : ''}</span>
    {/if}
  </div>

  {#if diff.sections.length === 0}
    <p class="muted">No changes recorded — file may already be U1-compatible.</p>
  {:else}
    <div class="sections">
      {#each diff.sections as section, i (section.title)}
        <div class="section card">
          <button
            class="section-header"
            onclick={() => toggle(i)}
            aria-expanded={expanded.has(i)}
          >
            <span class="check">✓</span>
            <span class="section-title">{section.title}</span>
            <span class="section-summary muted">{section.summary}</span>
            <span class="chevron" class:open={expanded.has(i)}>›</span>
          </button>

          {#if expanded.has(i)}
            <div class="section-body">
              {#if section.title === 'Printer identity'}
                <table>
                  <thead><tr><th>Key</th><th>From</th><th>To</th></tr></thead>
                  <tbody>
                    {#each section.details as row}
                      <tr>
                        <td class="mono">{row.key}</td>
                        <td class="from">{formatValue(row.from_value)}</td>
                        <td class="to">{formatValue(row.to_value)}</td>
                      </tr>
                    {/each}
                  </tbody>
                </table>

              {:else if section.title === 'Custom G-code'}
                <table>
                  <thead><tr><th>Block</th><th>Before</th><th>After</th></tr></thead>
                  <tbody>
                    {#each section.details as row}
                      <tr>
                        <td class="mono">{row.key}</td>
                        <td class="muted">{row.from_bytes} B</td>
                        <td>{row.to_bytes} B</td>
                      </tr>
                    {/each}
                  </tbody>
                </table>

              {:else if section.title === 'Keys dropped'}
                <div class="chip-list">
                  {#each section.details as row}
                    <span class="chip mono">{row.key}</span>
                  {/each}
                </div>

              {:else if section.title === 'Values clamped'}
                <table>
                  <thead><tr><th>Key</th><th>Was</th><th>Clamped to</th></tr></thead>
                  <tbody>
                    {#each section.details as row}
                      <tr>
                        <td class="mono">{row.key}</td>
                        <td class="from">{formatValue(row.from_value)}</td>
                        <td>{formatValue(row.to_value)}</td>
                      </tr>
                    {/each}
                  </tbody>
                </table>

              {:else if section.title === 'Filament rules applied'}
                {#each section.details as rule}
                  <div class="rule-match">
                    <div class="rule-name">
                      {rule.rule_name}
                      <span class="pill">priority {rule.priority}</span>
                    </div>
                    <div class="rule-sub">
                      <div>
                        <div class="label muted">Matched on</div>
                        {#each Object.entries(rule.matched_on) as [k, v]}
                          <div class="kv"><span class="mono">{k}</span>: {formatValue(v)}</div>
                        {/each}
                      </div>
                      <div>
                        <div class="label muted">Overrides applied</div>
                        {#each Object.entries(rule.overrides_applied) as [k, v]}
                          <div class="kv"><span class="mono">{k}</span>: {formatValue(v)}</div>
                        {/each}
                      </div>
                    </div>
                  </div>
                {/each}

              {:else if section.title === 'Filament slots'}
                <table>
                  <thead><tr><th>Filament</th><th>Source slot</th><th>Output</th></tr></thead>
                  <tbody>
                    {#each section.details as row}
                      <tr>
                        <td class="muted">{row.filament_id ?? '—'}</td>
                        <td>{row.from_index + 1}</td>
                        <td class:dropped={row.to_index < 0} class:passthrough={row.to_index >= 4}>
                          {#if row.to_index < 0}
                            dropped
                          {:else if row.to_index >= 4}
                            slot {row.to_index + 1} (Orca assigns)
                          {:else}
                            T{row.to_index + 1}
                          {/if}
                        </td>
                      </tr>
                    {/each}
                  </tbody>
                </table>

              {:else if section.title === 'Slice caches stripped'}
                <div class="chip-list">
                  {#each section.details as name}
                    <span class="chip mono">{name}</span>
                  {/each}
                </div>

              {:else if section.title === 'Filament swap pauses'}
                {@const byZ = Object.entries(
                  section.details.reduce((acc: Record<string, typeof section.details>, instr: typeof section.details[0]) => {
                    const key = String(instr.z);
                    (acc[key] = acc[key] || []).push(instr);
                    return acc;
                  }, {})
                ).sort(([a], [b]) => parseFloat(a) - parseFloat(b))}
                <div class="swap-instructions">
                  {#each byZ as [zKey, instrs], gi}
                    <div class="swap-group">
                      <div class="swap-group-header">
                        <span class="swap-stop">Stop {gi + 1}</span>
                        <span class="swap-z mono">after Z = {parseFloat(zKey).toFixed(2)} mm</span>
                        <span class="subtle swap-count">{instrs.length} spool{instrs.length > 1 ? 's' : ''} to swap</span>
                      </div>
                      {#each instrs as instr}
                        <div class="swap-row">
                          <span class="swap-head-badge">T{instr.toolhead}</span>
                          <div class="swap-swatch-pair">
                            <span class="swatch-sm" style="background:{instr.from_colour || '#888'}" title="Current: slot {instr.from_slot}"></span>
                            <span class="swap-arrow">→</span>
                            <span class="swatch-sm" style="background:{instr.to_colour || '#888'}" title="Load: slot {instr.to_slot}"></span>
                          </div>
                          <div class="swap-detail">
                            <span class="swap-detail-title">Toolhead {instr.toolhead} — remove spool and load new one</span>
                            <span class="subtle swap-detail-sub">
                              Unload {instr.from_colour || 'current'} · Load {instr.to_colour || 'new colour'}
                            </span>
                          </div>
                        </div>
                      {/each}
                    </div>
                  {/each}
                  <p class="subtle swap-note">When the print pauses, swap the listed spools, then press Resume. Each stop may require multiple spool changes — do them all before resuming.</p>
                </div>

              {:else}
                <pre class="detail-raw">{JSON.stringify(section.details, null, 2)}</pre>
              {/if}
            </div>
          {/if}
        </div>
      {/each}
    </div>
  {/if}

  <div class="download-footer">
    <a href={downloadUrl(jobId)} download={downloadName} class="download-btn large">
      Download {downloadName}
    </a>
    <p class="subtle">File expires in ~5 minutes — download now or convert again.</p>
  </div>
</div>

<style>
  .diff-view { display: flex; flex-direction: column; gap: 20px; }

  .header {
    display: flex;
    align-items: flex-start;
    justify-content: space-between;
    gap: 16px;
    flex-wrap: wrap;
  }
  .header h2 { margin: 0 0 6px; font-size: 18px; }
  .header-left { flex: 1; }
  .header-actions { display: flex; gap: 10px; align-items: center; flex-shrink: 0; }
  .accent { color: var(--accent); }
  .meta { font-size: 13px; }

  .painted-warning {
    padding: 12px 16px;
    background: color-mix(in srgb, var(--warn) 12%, var(--bg-elev));
    border: 1px solid color-mix(in srgb, var(--warn) 35%, transparent);
    border-radius: var(--radius);
    color: var(--warn);
    font-size: 13px;
    margin-bottom: 4px;
  }

  .pills { display: flex; flex-wrap: wrap; gap: 8px; }

  .sections { display: flex; flex-direction: column; gap: 6px; }

  .section { overflow: hidden; }

  .section-header {
    display: grid;
    grid-template-columns: 20px 1fr auto 20px;
    align-items: center;
    gap: 10px;
    width: 100%;
    padding: 14px 16px;
    background: transparent;
    border: none;
    border-radius: var(--radius-lg);
    cursor: pointer;
    text-align: left;
    font-size: 14px;
    transition: background var(--duration);
  }
  .section-header:hover { background: var(--bg-raised); }

  .check { color: var(--success); font-weight: 600; }
  .section-title { font-weight: 500; }
  .section-summary { font-size: 12px; }
  .chevron { color: var(--text-muted); transition: transform var(--duration); }
  .chevron.open { transform: rotate(90deg); }

  .section-body {
    padding: 0 16px 14px;
    border-top: 1px solid var(--border);
    margin-top: 0;
  }

  table {
    width: 100%;
    border-collapse: collapse;
    font-size: 12.5px;
    margin-top: 10px;
  }
  th {
    text-align: left;
    color: var(--text-subtle);
    font-weight: 500;
    padding: 6px 10px 6px 0;
    border-bottom: 1px solid var(--border);
    font-size: 11px;
    text-transform: uppercase;
    letter-spacing: 0.03em;
  }
  td {
    padding: 7px 10px 7px 0;
    border-bottom: 1px solid color-mix(in srgb, var(--border) 50%, transparent);
    color: var(--text);
    max-width: 280px;
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
  }
  td.from { color: var(--text-subtle); }
  td.dropped { color: var(--warn); }
  td.passthrough { color: var(--text-muted); font-style: italic; }

  .chip-list {
    display: flex;
    flex-wrap: wrap;
    gap: 6px;
    padding-top: 10px;
  }
  .chip {
    font-size: 11px;
    padding: 2px 8px;
    background: var(--bg-raised);
    border: 1px solid var(--border);
    border-radius: 4px;
    color: var(--text-muted);
  }

  .rule-match {
    background: var(--bg-raised);
    border-radius: var(--radius);
    padding: 12px 14px;
    margin-top: 10px;
  }
  .rule-name { font-weight: 500; display: flex; align-items: center; gap: 10px; }
  .rule-sub { display: grid; grid-template-columns: 1fr 1fr; gap: 12px; margin-top: 10px; }
  .label { font-size: 11px; text-transform: uppercase; letter-spacing: 0.04em; margin-bottom: 4px; }
  .kv { font-size: 12px; }

  .detail-raw {
    font-size: 11.5px;
    font-family: var(--font-mono);
    background: var(--bg-raised);
    padding: 10px 12px;
    border-radius: var(--radius);
    overflow: auto;
    max-height: 300px;
    color: var(--text-muted);
    margin-top: 10px;
  }

  .download-btn {
    display: inline-flex;
    align-items: center;
    background: var(--accent);
    color: #fff;
    border: 1px solid var(--accent);
    padding: 8px 16px;
    border-radius: var(--radius);
    font-weight: 500;
    cursor: pointer;
    transition: background var(--duration), border-color var(--duration);
    font-size: 13.5px;
    text-decoration: none;
  }
  .download-btn:hover { background: var(--accent-hover); border-color: var(--accent-hover); color: #fff; }
  .download-btn.large { padding: 12px 28px; font-size: 15px; }

  .swap-instructions { display: flex; flex-direction: column; gap: 12px; padding-top: 10px; }
  .swap-group {
    border: 1px solid var(--border);
    border-radius: var(--radius);
    overflow: hidden;
  }
  .swap-group-header {
    display: flex;
    align-items: center;
    gap: 10px;
    padding: 8px 12px;
    background: var(--bg-raised);
    border-bottom: 1px solid var(--border);
    font-size: 13px;
  }
  .swap-stop { font-weight: 600; color: var(--warn); }
  .swap-z { font-size: 12px; color: var(--text-muted); }
  .swap-count { margin-left: auto; font-size: 12px; }
  .swap-row {
    display: flex;
    align-items: center;
    gap: 12px;
    padding: 10px 12px;
    border-bottom: 1px solid color-mix(in srgb, var(--border) 40%, transparent);
    font-size: 13px;
  }
  .swap-row:last-child { border-bottom: none; }
  .swap-head-badge {
    font-weight: 700;
    font-size: 12px;
    padding: 2px 7px;
    border-radius: 4px;
    background: color-mix(in srgb, var(--accent) 15%, transparent);
    color: var(--accent);
    flex-shrink: 0;
    min-width: 28px;
    text-align: center;
  }
  .swap-swatch-pair { display: flex; align-items: center; gap: 6px; flex-shrink: 0; }
  .swap-arrow { font-size: 14px; color: var(--text-muted); }
  .swap-detail { display: flex; flex-direction: column; gap: 2px; }
  .swap-detail-title { font-weight: 500; }
  .swap-detail-sub { font-size: 11.5px; }
  .swatch-sm { width: 20px; height: 20px; border-radius: 4px; border: 1px solid color-mix(in srgb, var(--border) 60%, transparent); flex-shrink: 0; }
  .swap-note { margin: 4px 0 0; font-size: 12px; }

  .download-footer {
    display: flex;
    flex-direction: column;
    align-items: center;
    gap: 8px;
    padding: 20px;
    border-top: 1px solid var(--border);
  }
  .download-footer .subtle { margin: 0; }
</style>
